import {
  Instagram,
  Scan,
  Volume2,
  Video,
  VolumeOff,
  ImageIcon,
  File,
} from "@/public/icons/Svgs/index";
import { VideoOff } from "lucide-react";

export const videoArray = [
  { id: 1, name: "Audio to Text", link: "/video/audio-to-text" },
  { id: 2, name: "Resize Video", link: "/video/resize" },
  { id: 3, name: "Extract Audio", link: "/video/extract-audio" },
  { id: 4, name: "MOV to MP4", link: "/video/mov-to-mp4" },
  { id: 5, name: "TikTok Video Downloader", link: "/video/from-tiktok" },
  { id: 6, name: "Facebook Download", link: "/video/from-fb" },
  { id: 7, name: "MKV to MP4", link: "/video/mkv-to-mp4" },
  { id: 8, name: "Instagram Download", link: "/video/from-inst" },
  { id: 9, name: "Twitter Download", link: "/video/from-twitter" },
  { id: 10, name: "M4A to MP3", link: "/video//m4a-to-mp3" },
  { id: 11, name: "Video to WebP", link: "/video/to-webp" },
  { id: 11, name: "All Video Tools", link: "/tools/video" },
];

export const featuredVideoTools = [
  {
    title: "Compress Video",
    description: "Video Tools",
    paragraph: "Lessen the file size of a Video file",
    icon: Scan,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/compress",
  },
  {
    title: "Video to Gif",
    description: "Video Tools",
    paragraph: "Upload an MP4 and convert to animated GIF",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/to-gif",
  },
  {
    title: "Trim Video",
    description: "Video Tools",
    paragraph:
      "Select a start and stop of a video and download the trimmed video",
    icon: VideoOff,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/cutter",
  },
  {
    title: "MP4 to MP3",
    description: "Video Tools",
    paragraph: "Convert MP4 to MP3 audio",
    icon: Volume2,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/mp4-to-mp3",
  },
];

export const videoTools = [
  {
    title: "Instagram Download",
    description: "Video Tools",
    paragraph: "Download Video from Instagram",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: Instagram,
    link: "/video/from-inst",
  },
  {
    title: "TikTok Video Downloader",
    description: "Video Tools",
    paragraph: "Download Video from TikTok",
    icon: Video,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/from-tiktok",
  },
  {
    title: "Compress Video",
    description: "Video Tools",
    paragraph: "Lessen the file size of a Video file",
    icon: Scan,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/compress",
  },
  {
    title: "Youtube to Text",
    description: "Video Tools",
    paragraph: "Convert video to text",
    icon: Video,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/youtube-to-text",
  },
  {
    title: "MP4 to MP3",
    description: "Video Tools",
    paragraph: "Convert MP4 to MP3 audio",
    icon: Volume2,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/mp4-to-mp3",
  },
  {
    title: "Audio to Text",
    description: "Video Tools",
    paragraph: "Transcribe audio to text",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/audio-to-text",
  },
  {
    title: "Extract Audio from Video",
    description: "Video Tools",
    paragraph: "Extract audio from your video",
    icon: Video,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/video/extract-audio",
  },
  {
    title: "Video to Gif",
    description: "Video Tools",
    paragraph: "Upload an MP4 and convert to animated GIF",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/to-gif",
  },
  {
    title: "YouTube Transcript Generator",
    description: "Video Tools",
    paragraph: "Transcribe YouTube Video",
    icon: Video,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/youtube-transcript",
  },
  {
    title: "Twitter Download",
    description: "Video Tools",
    paragraph: "Download Video from Twitter",
    icon: Video,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/video/from-twitter",
  },
  {
    title: "Facebook Download",
    description: "Video Tools",
    paragraph: "Download Video from Facebook",
    icon: Video,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/video/from-fb",
  },
  {
    title: "Trim Video",
    description: "Video Tools",
    paragraph:
      "Select a start and stop of a video and download the trimmed video",
    icon: VideoOff,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/cutter",
  },
  {
    title: "Video to Text",
    description: "Video Tools",
    paragraph: "Transcribe video to text",
    icon: Video,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/to-text",
  },
  {
    title: "MOV to MP4",
    description: "Video Tools",
    paragraph: "Convert MOV to MP4",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mov-to-mp4",
  },
  {
    title: "Resize Video",
    description: "Video Tools",
    paragraph: "Resize a video's resolution and maintain aspect ratio",
    icon: Video,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/resize",
  },
  {
    title: "M4A to MP3",
    description: "Video Tools",
    paragraph: "Convert M4A to MP3 audio",
    icon: Volume2,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/m4a-to-mp3",
  },
  {
    title: "Mute Video",
    description: "Video Tools",
    paragraph: "Upload a video and download the video with no sound",
    icon: VolumeOff,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mute",
  },
  {
    title: "Add Subtitles",
    description: "Video Tools",
    paragraph: "Add subtitles to video",
    icon: Video,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/add-subtitles",
  },
  {
    title: "Video to WebP",
    description: "Video Tools",
    paragraph: "Upload a video file to convert to WebP",
    icon: Video,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/to-webp",
  },
  {
    title: "MP4 to GIF",
    description: "Video Tools",
    paragraph: "Convert MP4 to GIF",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mp4-to-gif",
  },
  {
    title: "MP4 to AVI",
    description: "Video Tools",
    paragraph: "Convert MP4 to AVI",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mp4-to-avi",
  },
  {
    title: "MKV to MP4",
    description: "Video Tools",
    paragraph: "Convert MKV to MP4",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mkv-to-mp4",
  },
  {
    title: "WEBM to MP4",
    description: "Video Tools",
    paragraph: "Convert WEBM to MP4",
    icon: Volume2,
    iconColor: "#10D0D5",
    divColor: "E3FCFD",
    link: "/video/webm-to-mp4",
  },
  {
    title: "OGG to MP3",
    description: "Video Tools",
    paragraph: "Convert OGG to MP3 audio",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/ogg-to-mp3",
  },
  {
    title: "MP4 to MOV",
    description: "Video Tools",
    paragraph: "Convert MP4 to MOV",
    icon: Volume2,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/video/mp4-to-mov",
  },
  {
    title: "MOV to GIF",
    description: "Video Tools",
    paragraph: "Convert MOV to GIF",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/mov-to-gif",
  },
  {
    title: "AVI to MP4",
    description: "Video Tools",
    paragraph: "Convert AVI to MP4",
    icon: Volume2,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/video/avi-to-mp4",
  },
  {
    title: "MP4 to WEBM",
    description: "Video Tools",
    paragraph: "Convert MP4 to WEBM",
    icon: Volume2,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/mp4-to-webm",
  },
  {
    title: "MOV to MP3",
    description: "Video Tools",
    paragraph: "Convert MOV to MP3 audio",
    icon: Volume2,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/video/mov-to-mp3",
  },
  {
    title: "MP4 to WAV",
    description: "Video Tools",
    paragraph: "Convert MP4 to WAV audio",
    icon: File,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/video/mp4-to-wav",
  },
  {
    title: "M4A to WAV",
    description: "Video Tools",
    paragraph: "Convert M4A to WAV audio",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/m4a-to-wav",
  },
  {
    title: "AAC to MP3",
    description: "Video Tools",
    paragraph: "Convert AAC to MP3 audio",
    icon: Volume2,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/video/aac-to-mp3",
  },
  {
    title: "MKV to MP3",
    description: "Video Tools",
    paragraph: "Convert MKV to MP3 audio",
    icon: Volume2,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/video/mkv-to-mp3",
  },
  {
    title: "Compress MOV",
    description: "Video Tools",
    paragraph: "Compress MOV video",
    icon: Video,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/compress-mov",
  },
  {
    title: "WEBM to MP3",
    description: "Video Tools",
    paragraph: "Convert WEBM to MP3",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/webm-to-mp3",
  },
  {
    title: "Transcribe Podcast",
    description: "Video Tools",
    paragraph: "Transcribe Podcast",
    icon: File,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/transcribe-podcast",
  },
  {
    title: "GIF to MOV",
    description: "Video Tools",
    paragraph: "Convert animated GIF to MOV Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/gif-to-mov",
  },
  {
    title: "MOV to AVI",
    description: "Video Tools",
    paragraph: "Convert MOV to AVI",
    icon: Video,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/mov-to-avi",
  },
  {
    title: "M4A to MP4",
    description: "Video Tools",
    paragraph: "Convert M4A to MP4",
    icon: Volume2,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/m4a-to-mp4",
  },
  {
    title: "GIF to WEBM",
    description: "Video Tools",
    paragraph: "Convert animated GIF to WEBM Online",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/gif-to-webm",
  },
  {
    title: "OGG to WAV",
    description: "Video Tools",
    paragraph: "Convert OGG to WAV",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/ogg-to-wav",
  },
  {
    title: "WEBM to MOV",
    description: "Video Tools",
    paragraph: "Convert WEBM to MOV",
    icon: Video,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/webm-to-mov",
  },
  {
    title: "MP4 to OGG",
    description: "Video Tools",
    paragraph: "Convert MP4 to OGG audio",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mp4-to-ogg",
  },
  {
    title: "AVI to MOV",
    description: "Video Tools",
    paragraph: "Convert AVI to MOV",
    icon: Video,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/video/avi-to-mov",
  },
  {
    title: "MKV to AVI",
    description: "Video Tools",
    paragraph: "Convert MKV to AVI",
    icon: Video,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/mkv-to-avi",
  },
  {
    title: "MKV to MOV",
    description: "Video Tools",
    paragraph: "Convert MKV to MOV",
    icon: Video,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/mkv-to-mov",
  },
  {
    title: "AVI to MP3",
    description: "Video Tools",
    paragraph: "Convert AVI to MP3 audio",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/avi-to-mp3",
  },
  {
    title: "MOV to WAV",
    description: "Video Tools",
    paragraph: "Convert MOV to WAV audio",
    icon: Volume2,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/mov-to-wav",
  },
  {
    title: "MKV to GIF",
    description: "Video Tools",
    paragraph: "Convert MKV to GIF",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/mkv-to-gif",
  },
  {
    title: "AAC to MP4",
    description: "Video Tools",
    paragraph: "Convert AAC to MP4",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/aac-to-mp4",
  },
  {
    title: "AVI to MKV",
    description: "Video Tools",
    paragraph: "Convert AVI to MKV",
    icon: Video,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/avi-to-mkv",
  },
  {
    title: "AVI to GIF",
    description: "Video Tools",
    paragraph: "Convert AVI to GIF",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/avi-to-gif",
  },
  {
    title: "AAC to WAV",
    description: "Video Tools",
    paragraph: "Convert AAC to WAV audio",
    icon: Volume2,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/aac-to-wav",
  },
  {
    title: "Compress AVI",
    description: "Video Tools",
    paragraph: "Compress AVI video",
    icon: Video,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/compress-avi",
  },
  {
    title: "Compress MKV",
    description: "Video Tools",
    paragraph: "Compress MKV video",
    icon: Video,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/compress-mkv",
  },
  {
    title: "Summarize Podcast",
    description: "Video Tools",
    paragraph: "Summarize Podcast",
    icon: File,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/summarize-podcast",
  },
  {
    title: "AAC to M4R",
    description: "Video Tools",
    paragraph: "Convert AAC to M4R audio",
    icon: Volume2,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/aac-to-m4r",
  },
  {
    title: "AAC to FLAC",
    description: "Video Tools",
    paragraph: "Convert AAC to FLAC audio",
    icon: Volume2,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/aac-to-flac",
  },
];
