import { CircleUser, File } from "lucide-react";
import ImageGenerator from "@/public/images/Home/Imagegenerator.png";
import ImageCompressor from "@/public/images/Home/ImageCompressor.png";
import UpscaleImage from "@/public/images/Home/UpscaleImage.png";
import { ImageIcon, Video, FileText } from "@/public/icons/Svgs";

export const imageToolsArray = [
  { id: 1, name: "Blur Background", link: "/image/blur-background" },
  { id: 2, name: "Colorize Photo", link: "/image/colorize-photo" },
  { id: 3, name: "Combine Images", link: "/image/combine-maker" },
  { id: 4, name: "Collage Maker", link: "/image/collage-maker" },
  { id: 5, name: "Remove Watermark", link: "/image/remove-watermark-photo" },
  { id: 6, name: "Chart Maker", link: "/image/chart-maker" },
  {
    id: 7,
    name: "Transparent Background",
    link: "/image/make-transparent-background",
  },
  { id: 8, name: "Crop Image", link: "/image/crop" },
  { id: 9, name: "Add Border To Image", link: "/image/border" },
  { id: 10, name: "Image Splitter", link: "/image/split" },
  { id: 11, name: "Add Text to Image", link: "/image/text-to-image" },
  { id: 12, name: "Pixelate Image", link: "/image/pixelate" },
  { id: 13, name: "Make Round Image", link: "/image/crop-circle" },
  { id: 14, name: "Black & White", link: "/image/grayscale" },
  { id: 15, name: "Flip Image", link: "/image/flip" },
  { id: 16, name: "Unblur IMG", link: "/image/unblur" },
  { id: 17, name: "HEIC To JPG", link: "/image/heic-to-jpg" },
  { id: 18, name: "All Image Tools", link: "/tools/image" },
];

export const featuredImageTools = [
  {
    title: "Remove Person From Photo",
    description: "Image tools",
    paragraph: "Remove a Person from photo",
    icon: ImageIcon,
    iconColor: "#FF7919",
    bgColor: "#FFEDE0",
    link: "/image/remove-person",
  },
  {
    title: "Profile Photo Maker",
    description: "Image Tools",
    paragraph: "Create round profile photo from image",
    icon: CircleUser,
    iconColor: "#79DC47",
    bgColor: "#ECFAE5",
    link: "/image/profile-photo",
  },
  {
    title: "Image To Text",
    description: "Image Tools",
    paragraph: "Extract text from images",
    icon: FileText,
    iconColor: "#FF7919",
    bgColor: "#FFEDE0",
    link: "/image/to-text",
  },
  {
    title: "AI Image Generator",
    description: "Image Tools",
    paragraph: "AI Image Generator",
    icon: ImageIcon,
    iconColor: "#FF7919",
    bgColor: "#FFEDE0",
    link: "/image/ai-image-generator",
  },
  {
    title: "Remove Objects from Photo",
    description: "Image Tools",
    paragraph: "Remove objects from photo",
    icon: ImageIcon,
    iconColor: "#FF7919",
    bgColor: "#FFEDE0",
    link: "/image/remove-objects",
  },
];

export const ImageCardTools = [
  {
    img: ImageGenerator,
    title: "Resize Dimensions",
    description: "Resize your Image",
    link: "/image/resize",
    bgColor: "#ECFAE5",
    iconColor: "#9BE575",
  },
  {
    img: ImageCompressor,
    title: "Compress",
    description: "Compress your Image",
    link: "/image/compress",
    bgColor: "#E2F0FE",
    iconColor: "#6EB3F7",
  },
  {
    img: UpscaleImage,
    title: "Increase Image Resolution",
    description: "Increase the resolution of your Image",
    link: "/image/upscale",
    bgColor: "#FCF4E9",
    iconColor: "#FF6D86",
  },
];
export const imagePageToolArray = [
  {
    title: "PDF to JPG",
    description: "Pdf Tools",
    paragraph: "Convert PDF to JPG and download each page as an image",
    icon: File,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/pdf/to-jpg",
  },
  {
    title: "Upscale Image",
    description: "Image Tools",
    paragraph: "Increase the resolution of your image",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/upscale",
  },
  {
    title: "Image To Text",
    description: "Image Tools",
    paragraph: "Extract text from images",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/to-text",
  },

  {
    title: "HEIC to JPG",
    description: "Image Tools",
    paragraph: "Convert an iPhone HEIC image to JPG",
    icon: ImageIcon,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/image/heic-to-jpg",
  },
  {
    title: "Blur Background",
    description: "Image Tools",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/blur-background",
  },
  {
    title: "Remove Person from Photo",
    description: "Image Tools",
    paragraph: "Remove a person from photo",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/remove-person",
  },
  {
    title: "WebP to JPG",
    description: "Image Tools",
    paragraph: "Upload a WebP image and download as JPG",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/webp-to-jpg",
  },
  {
    title: "Unblur Image",
    description: "Image Tools",
    paragraph: "Unblur your image",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/unblur",
  },
  {
    title: "Cleanup Picture",
    description: "Image Tools",
    paragraph: "Cleanup picture",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/cleanup-picture",
  },
  {
    title: "Colorize Photo",
    description: "Image Tools",
    paragraph: "Colorize your photo",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/colorize-photo",
  },
  {
    title: "PNG to JPG",
    description: "Image Tools",
    paragraph: "Convert a PNG image to JPG",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/png-to-jpg",
  },
  {
    title: "WEBP to PNG",
    description: "Image Tools",
    paragraph: "Convert a WEBP image to PNG",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/webp-to-png",
  },
  {
    title: "Crop Image",
    description: "Image Tools",
    paragraph: "Crop your image",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/crop",
  },
  {
    title: "Make Background Transparent",
    description: "Image Tools",
    paragraph: "Make background transparent",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/make-transparent-background",
  },
  {
    title: "Combine Images",
    description: "Image Tools",
    paragraph: "Combine multiple images online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/combine-maker",
  },
  {
    title: "JPG to PNG",
    description: "Image Tools",
    paragraph: "Convert a JPG image to PNG",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/jpg-to-png",
  },
  {
    title: "PNG to WEBP",
    description: "Image Tools",
    paragraph: "Convert a PNG image to WEBP",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/png-to-webp",
  },
  {
    title: "JPG to WEBP",
    description: "Image Tools",
    paragraph: "Convert a JPG image to WEBP",
    icon: ImageIcon,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/image/jpg-to-webp",
  },
  {
    title: "Make Round Image",
    description: "Image Tools",
    paragraph: "Make round images",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/crop-circle",
  },
  {
    title: "Remove Watermark",
    description: "Image Tools",
    paragraph: "Remove watermark from photo",
    icon: ImageIcon,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/image/remove-watermark",
  },
  {
    title: "AI Image Generator",
    description: "Image Tools",
    paragraph: "AI Image Generator",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/ai-image-generator",
  },

  {
    title: "Compress Image Size",
    description: "Image Tools",
    paragraph: "Compress your image",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/compress",
  },
  {
    title: "Remove Background from Image",
    description: "Image Tools",
    paragraph: "Easily Remove the Background from an image",
    icon: ImageIcon,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/image/remove-bg",
  },
  {
    title: "Resize Image Dimensions",
    description: "Image Tools",
    paragraph: "Resize your image",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/resize",
  },
  {
    title: "Profile Photo Maker",
    description: "Image Tools",
    paragraph: "Create round profile photo from image",
    icon: CircleUser,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/image/profile-photo",
  },
  {
    title: "Remove Objects from Photo",
    description: "Image Tools",
    paragraph: "Remove objects from photo",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/remove-objects",
  },
  {
    title: "PNG to SVG",
    description: "Image Tools",
    paragraph: "Convert a PNG image to SVG",
    icon: ImageIcon,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/image/png-to-svg",
  },
  {
    title: "Black & White",
    description: "Image Tools",
    paragraph: "Make your photo black & white",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/grayscale",
  },
  {
    title: "Add Text to an Image",
    description: "Image Tools",
    paragraph: "Add text to an image online",
    icon: ImageIcon,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/image/text-to-image",
  },
  {
    title: "JPG to SVG",
    description: "Image Tools",
    paragraph: "Convert a JPG image to SVG",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/jpg-to-svg",
  },
  {
    title: "HEIC to PNG",
    description: "Image Tools",
    paragraph: "Convert a HEIC image to PNG",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/heic-to-png",
  },
  {
    title: "Image Splitter",
    description: "Image Tools",
    paragraph: "Cut image into pieces",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/split",
  },
  {
    title: "Add Images",
    description: "Image Tools",
    paragraph: "Add images to Image",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/add-images",
  },
  {
    title: "Pixelate Image",
    description: "Image Tools",
    paragraph: "Pixelate your photo",
    icon: ImageIcon,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/image/pixelate",
  },
  {
    title: "Translate Image",
    description: "Image Tools",
    paragraph: "Translate your image",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/translate",
  },
  {
    title: "Add Border to Image",
    description: "Image Tools",
    paragraph: "Add a border to your image",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/border",
  },
  {
    title: "Collage Maker",
    description: "Image Tools",
    paragraph: "Create Photo Collages Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/collage-maker",
  },
  {
    title: "SVG to PNG",
    description: "Image Tools",
    paragraph: "Convert a SVG image to PNG free",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/svg-to-png",
  },
  {
    title: "GIF to MP4",
    description: "Video Tools",
    paragraph: "Convert animated GIF to MP4 Online",
    icon: Video,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/image/gif-to-mp4",
  },
  {
    title: "JPG to GIF",
    description: "Image Tools",
    paragraph: "Convert a JPG Image to GIF Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/jpg-to-gif",
  },
  {
    title: "Flip Image",
    description: "Image Tools",
    paragraph: "Flip Image",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/flip",
  },
  {
    title: "TIFF to JPG",
    description: "Image Tools",
    paragraph: "Convert a TIFF Image to JPG Online",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/tiff-to-jpg",
  },
  {
    title: "WEBP to GIF",
    description: "Image Tools",
    paragraph: "Convert a WEBP Image to GIF Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/webp-to-gif",
  },
  {
    title: "View Metadata",
    description: "Image Tools",
    paragraph: "View metadata for your image",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/metadata",
  },
  {
    title: "PNG to EPS",
    description: "Image Tools",
    paragraph: "Convert a PNG Image to EPS Online",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/png-to-eps",
  },
  {
    title: "JPG to TIFF",
    description: "Image Tools",
    paragraph: "Convert a JPG Image to TIFF Online",
    icon: ImageIcon,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/image/jpg-to-tiff",
  },
  {
    title: "PNG to GIF",
    description: "Image Tools",
    paragraph: "Convert a PNG Image to GIF Online",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/png-to-gif",
  },
  {
    title: "PSD to JPG",
    description: "Image Tools",
    paragraph: "Convert a PSD Image to JPG Online",
    icon: ImageIcon,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/image/psd-to-jpg",
  },
  {
    title: "EPS to PNG",
    description: "Image Tools",
    paragraph: "Convert an EPS image to PNG",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/eps-to-png",
  },
  {
    title: "PSD to PNG",
    description: "Image Tools",
    paragraph: "Convert a PSD Image to PNG Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/psd-to-png",
  },
  {
    title: "Chart Maker",
    description: "Image Tools",
    paragraph: "Download a chart as image",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/chart-maker",
  },
  {
    title: "GIF to JPG",
    description: "Image Tools",
    paragraph: "Convert a GIF Image to JPG Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/gif-to-jpg",
  },
  {
    title: "TIFF to PNG",
    description: "Image Tools",
    paragraph: "Convert a TIFF Image to PNG Online",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/tiff-to-png",
  },
  {
    title: "GIF to PNG",
    description: "Image Tools",
    paragraph: "Convert a GIF Image to PNG Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/gif-to-png",
  },
  {
    title: "PSD to AI",
    description: "Image Tools",
    paragraph: "Convert a PSD Image to AI Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/psd-to-ai",
  },
  {
    title: "EPS to JPG",
    description: "Image Tools",
    paragraph: "Convert an EPS Image to JPG Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/eps-to-jpg",
  },
  {
    title: "PNG to TIFF",
    description: "Image Tools",
    paragraph: "Convert a PNG Image to TIFF Online",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/png-to-tiff",
  },
  {
    title: "EPS to SVG",
    description: "Image Tools",
    paragraph: "Convert a EPS Image to SVG Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/eps-to-svg",
  },
  {
    title: "Font Awesome to PNG",
    description: "Image Tools",
    paragraph: "Convert Font Awesome to PNG",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/font-to-png",
  },
  {
    title: "TIFF To Text",
    description: "Image Tools",
    paragraph: "TIFF To Text",
    icon: FileText,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/image/tiff-to-text",
  },
  {
    title: "GIF to APNG",
    description: "Image Tools",
    paragraph: "Convert animated GIF Image to APNG Online",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/gif-to-apng",
  },
  {
    title: "PSD to SVG",
    description: "Image Tools",
    paragraph: "Convert a PSD Image to SVG Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/psd-to-svg",
  },
  {
    title: "TIFF to SVG",
    description: "Image Tools",
    paragraph: "Convert a TIFF Image to SVG Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/tiff-to-svg",
  },
  {
    title: "JPG to AVIF",
    description: "Image Tools",
    paragraph: "Convert a JPG Image to AVIF Online",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/image/jpg-to-avif",
  },
  {
    title: "VSDX To PDF",
    description: "Image Tools",
    paragraph: "VSDX To PDF",
    icon: FileText,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/image/vsdx-to-pdf",
  },
  {
    title: "VSDX To DOCX",
    description: "Image Tools",
    paragraph: "VSDX To DOCX",
    icon: FileText,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/image/vsdx-to-docx",
  },
  {
    title: "VSDX To PPTX",
    description: "Image Tools",
    paragraph: "VSDX To PPTX",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/vsdx-to-pptx",
  },
  {
    title: "PNG to AVIF",
    description: "Image Tools",
    paragraph: "Convert a PNG Image to AVIF Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/png-to-avif",
  },
  {
    title: "VSD To PDF",
    description: "Image Tools",
    paragraph: "VSD To PDF",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image/vsd-to-pdf",
  },
  {
    title: "VSDX To JPG",
    description: "Image Tools",
    paragraph: "VSDX To JPG",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/vsdx-to-jpg",
  },
  {
    title: "VSD To PPTX",
    description: "Image Tools",
    paragraph: "VSD To PPTX",
    icon: FileText,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/image/vsd-to-pptx",
  },
  {
    title: "WEBP to AVIF",
    description: "Image Tools",
    paragraph: "Convert a WEBP Image to AVIF Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/image/webp-to-avif",
  },
  {
    title: "VSD To DOCX",
    description: "Image Tools",
    paragraph: "VSD To DOCX",
    icon: FileText,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/vsd-to-docx",
  },
  {
    title: "GIF to AVIF",
    description: "Image Tools",
    paragraph: "Convert a GIF Image to AVIF Online",
    icon: ImageIcon,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/image/gif-to-avif",
  },
  {
    title: "HEIC to AVIF",
    description: "Image Tools",
    paragraph: "Convert a HEIC Image to AVIF Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/image/heic-to-avif",
  },
];
