import {
  Instagram,
  Scan,
  Volume2,
  CircleUser,
  Video,
  VolumeOff,
  FileText,
  File,
  GitMerge,
  Lock,
  LockOpen,
  PenLine,
  RefreshCcw,
  ImageIcon,
  Scissors,
} from "@/public/icons/Svgs";
import { MessageCircle, VideoOff } from "lucide-react";

export const toolsArray = [
  {
    title: "Merge PDF",
    description: "Pdf Tools",
    paragraph: "Merge 2 or more PDF files into a single PDF file",
    icon: GitMerge,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/merge",
  },
  {
    title: "Edit PDF",
    description: "Pdf Tools",
    paragraph: "Free PDF Editor",
    icon: FileText,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/pdf/edit",
  },
  {
    title: "PDF to JPG",
    description: "Pdf Tools",
    paragraph: "Convert PDF to JPG and download each page as an image",
    icon: FileText,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/pdf/to-jpg",
  },
  {
    title: "JPG to PDF",
    description: "Pdf Tools",
    paragraph: "Upload images and receive as a PDF",
    icon: FileText,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/pdf/from-jpg",
  },
  {
    title: "Compress PDF",
    description: "Pdf Tools",
    paragraph: "Lessen the file size of a PDF file",
    icon: Scan,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/pdf/compress",
  },
  {
    title: "Change Background of Photo",
    description: "Image Tools",
    paragraph: "Change Background of Image",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/change-bg-photo",
  },
  {
    title: "Split PDF",
    description: "Pdf Tools",
    paragraph: "Split into one or multiple PDF files",
    icon: Scissors,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/split",
  },
  {
    title: "PDF to Word",
    description: "Pdf Tools",
    paragraph: "Convert a PDF to Word Document",
    icon: FileText,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/pdf/to-word",
  },
  {
    title: "Word to PDF",
    description: "Pdf Tools",
    paragraph: "Convert a Word Document to PDF",
    icon: FileText,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/word-to-pdf",
  },
  {
    title: "Unlock PDF",
    description: "Pdf Tools",
    paragraph: "Remove the password from a PDF file (requires the password)",
    icon: LockOpen,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/pdf/unlock",
  },
  {
    title: "PDF to Excel",
    description: "Pdf Tools",
    paragraph: "Convert from PDF to XLSX",
    icon: FileText,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/pdf/to-excel",
  },
  {
    title: "PDF to Powerpoint",
    description: "Pdf Tools",
    paragraph: "Upload a PDF and Download as a PowerPoint Presentation",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/to-ppt",
  },
  {
    title: "PNG to PDF",
    description: "Pdf Tools",
    paragraph: "Upload images and receive as a PDF",
    icon: FileText,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/pdf/from-png",
  },
  {
    title: "EPUB to PDF",
    description: "Pdf Tools",
    paragraph: "Convert EPUB file to PDF file",
    icon: FileText,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/pdf/from-epub",
  },
  {
    title: "Crop PDF",
    description: "Pdf Tools",
    paragraph: "Free PDF cropper",
    icon: FileText,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/pdf/crop",
  },
  {
    title: "Powerpoint to PDF",
    description: "Pdf Tools",
    paragraph: "Upload a Powerpoint presentation and Download as a PDF",
    icon: FileText,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/pdf/from-ppt",
  },
  {
    title: "PDF to PNG",
    description: "Pdf Tools",
    paragraph: "Convert PDF to PNG and download each page as an image",
    icon: FileText,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/pdf/to-png",
  },
  {
    title: "PDF Translator",
    description: "Pdf Tools",
    paragraph: "Translate your PDF",
    icon: FileText,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/pdf/translator",
  },
  {
    title: "PDF Page Deleter",
    description: "Pdf Tools",
    paragraph: "Delete 1 or more pages from a PDF",
    icon: FileText,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/pdf/delete",
  },
  {
    title: "URL to PDF",
    description: "Pdf Tools",
    paragraph: "Enter a URL and receive the web page as a PDF",
    icon: FileText,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/pdf/from-url",
  },
  {
    title: "Rotate PDF",
    description: "Pdf Tools",
    paragraph: "Rotate one or more pages in a PDF file",
    icon: RefreshCcw,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/pdf/rotate",
  },
  {
    title: "Extract Images PDF",
    description: "Pdf Tools",
    paragraph: "Download the images from a PDF",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/extract-img",
  },
  {
    title: "Rearrange PDF",
    description: "Pdf Tools",
    paragraph: "Rearrange pages of PDF file",
    icon: FileText,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/pdf/rearrange",
  },
  {
    title: "Create PDF",
    description: "Pdf Tools",
    paragraph: "Free PDF Creator",
    icon: FileText,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/pdf/create",
  },
  {
    title: "PDF to EPUB",
    description: "Pdf Tools",
    paragraph: "Convert PDF file to EPUB file",
    icon: FileText,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/pdf/to-epub",
  },
  {
    title: "eSign PDF",
    description: "Pdf Tools",
    paragraph: "E-sign a PDF with a font or with your signature",
    icon: PenLine,
    iconColor: "#FF7C1E",
    divColor: "#FFEDE0",
    link: "/pdf/sign",
  },
  {
    title: "Protect PDF",
    description: "Pdf Tools",
    paragraph: "Add a password to a PDF file",
    icon: Lock,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/pdf/protect",
  },
  {
    title: "PDF Watermark Remover",
    description: "Pdf Tools",
    paragraph: "Remove Watermark from PDF",
    icon: FileText,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/pdf/remove-watermark",
  },
  {
    title: "PDF to CSV",
    description: "Pdf Tools",
    paragraph: "Extract tables from PDF to CSV",
    icon: FileText,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/pdf/to-csv",
  },
  {
    title: "Add Numbers to PDF",
    description: "Pdf Tools",
    paragraph: "Add page numbers to a PDF file",
    icon: FileText,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/pdf/add-pages",
  },
  {
    title: "Add Watermark",
    description: "Pdf Tools",
    paragraph: "Stamp an image over your PDF",
    icon: FileText,
    iconColor: "#FF7C1E",
    divColor: "#FFEDE0",
    link: "/pdf/watermark",
  },
  {
    title: "Images to PDF",
    description: "Pdf Tools",
    paragraph: "Add images to PDF online",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/pdf/from-png",
  },
  {
    title: "HEIC to PDF",
    description: "Pdf Tools",
    paragraph: "Upload images and receive as a PDF",
    icon: FileText,
    iconColor: "#FF7C1E",
    divColor: "#FFEDE0",
    link: "/pdf/from-heic",
  },
  {
    title: "Annotate PDF",
    description: "Pdf Tools",
    paragraph: "Free PDF Editor",
    icon: File,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/pdf/annotate",
  },
  {
    title: "TIFF to PDF",
    description: "Pdf Tools",
    paragraph: "Upload images and receive as a PDF",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/from-tiff",
  },
  {
    title: "Add Text",
    description: "Pdf Tools",
    paragraph: "Add Text to PDF",
    icon: FileText,
    iconColor: "#FF7C1E",
    divColor: "#FFEDE0",
    link: "/pdf/add-text",
  },
  {
    title: "MOBI to PDF",
    description: "Pdf Tools",
    paragraph: "Convert MOBI file to PDF file",
    icon: Lock,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/pdf/from-mobi",
  },
  {
    title: "PDF to MOBI",
    description: "Pdf Tools",
    paragraph: "Convert PDF file to MOBI file",
    icon: Lock,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/pdf/to-mobi",
  },
  {
    title: "PDF to TIFF",
    description: "Pdf Tools",
    paragraph: "Convert PDF to TIFF and download each page as an image",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/to-tiff",
  },
  {
    title: "AZW3 to PDF",
    description: "Pdf Tools",
    paragraph: "Convert AZW3 file to PDF file",
    icon: FileText,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/pdf/to-azw3",
  },
  {
    title: "PDF to AZW3",
    description: "Pdf Tools",
    paragraph: "Convert PDF file to AZW3 file",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/from-azw3",
  },
  {
    title: "PDF to Text",
    description: "Pdf Tools",
    paragraph: "Convert a PDF to Text",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/to-text",
  },
  {
    title: "WEBP to PDF",
    description: "Pdf Tools",
    paragraph: "Upload images and receive as a PDF",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/from-webp",
  },
  {
    title: "MS Outlook to PDF",
    description: "Pdf Tools",
    paragraph: "Upload a MS Outlook file and download as a PDF",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/from-msg",
  },
  {
    title: "Extract text from PDF",
    description: "Pdf Tools",
    paragraph: "Extract text from PDF document",
    icon: File,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/pdf/extract-text",
  },
  {
    title: "GIF to PDF",
    description: "Pdf Tools",
    paragraph: "Upload images and receive as a PDF",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/pdf/from-gif",
  },
  {
    title: "EPS to PDF",
    description: "Pdf Tools",
    paragraph: "Upload images and receive as a PDF",
    icon: File,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/pdf/from-eps",
  },
  {
    title: "Instagram Download",
    description: "Video Tools",
    paragraph: "Download Video from Instagram",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: Instagram,
    link: "/video/from-inst",
  },
  {
    title: "TikTok Video Downloader",
    description: "Video Tools",
    paragraph: "Download Video from TikTok",
    icon: Video,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/from-tiktok",
  },
  {
    title: "Compress Video",
    description: "Video Tools",
    paragraph: "Lessen the file size of a Video file",
    icon: Scan,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/compress",
  },
  {
    title: "Youtube to Text",
    description: "Video Tools",
    paragraph: "Convert video to text",
    icon: Video,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/youtube-to-text",
  },
  {
    title: "MP4 to MP3",
    description: "Video Tools",
    paragraph: "Convert MP4 to MP3 audio",
    icon: Volume2,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/mp4-to-mp3",
  },
  {
    title: "Audio to Text",
    description: "Video Tools",
    paragraph: "Transcribe audio to text",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/audio-to-text",
  },
  {
    title: "Extract Audio from Video",
    description: "Video Tools",
    paragraph: "Extract audio from your video",
    icon: Video,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/video/extract-audio",
  },
  {
    title: "Video to Gif",
    description: "Video Tools",
    paragraph: "Upload an MP4 and convert to animated GIF",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/to-gif",
  },
  {
    title: "YouTube Transcript Generator",
    description: "Video Tools",
    paragraph: "Transcribe YouTube Video",
    icon: Video,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/video/youtube-transcript",
  },
  {
    title: "Twitter Download",
    description: "Video Tools",
    paragraph: "Download Video from Twitter",
    icon: Video,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/video/from-twitter",
  },
  {
    title: "Facebook Download",
    description: "Video Tools",
    paragraph: "Download Video from Facebook",
    icon: Video,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/video/from-fb",
  },
  {
    title: "Trim Video",
    description: "Video Tools",
    paragraph:
      "Select a start and stop of a video and download the trimmed video",
    icon: VideoOff,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/cutter",
  },
  {
    title: "Video to Text",
    description: "Video Tools",
    paragraph: "Transcribe video to text",
    icon: Video,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/to-text",
  },
  {
    title: "MOV to MP4",
    description: "Video Tools",
    paragraph: "Convert MOV to MP4",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mov-to-mp4",
  },
  {
    title: "Resize Video",
    description: "Video Tools",
    paragraph: "Resize a video's resolution and maintain aspect ratio",
    icon: Video,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/resize",
  },
  {
    title: "M4A to MP3",
    description: "Video Tools",
    paragraph: "Convert M4A to MP3 audio",
    icon: Volume2,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/m4a-to-mp3",
  },
  {
    title: "Mute Video",
    description: "Video Tools",
    paragraph: "Upload a video and download the video with no sound",
    icon: VolumeOff,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mute",
  },
  {
    title: "Add Subtitles",
    description: "Video Tools",
    paragraph: "Add subtitles to video",
    icon: Video,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/add-subtitles",
  },
  {
    title: "Video to WebP",
    description: "Video Tools",
    paragraph: "Upload a video file to convert to WebP",
    icon: Video,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/to-webp",
  },
  {
    title: "MP4 to GIF",
    description: "Video Tools",
    paragraph: "Convert MP4 to GIF",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mp4-to-gif",
  },
  {
    title: "MP4 to AVI",
    description: "Video Tools",
    paragraph: "Convert MP4 to AVI",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mp4-to-avi",
  },
  {
    title: "MKV to MP4",
    description: "Video Tools",
    paragraph: "Convert MKV to MP4",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/mkv-to-mp4",
  },
  {
    title: "WEBM to MP4",
    description: "Video Tools",
    paragraph: "Convert WEBM to MP4",
    icon: Volume2, // Add icon
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/video/webm-to-mp4",
  },
  {
    title: "OGG to MP3",
    description: "Video Tools",
    paragraph: "Convert OGG to MP3 audio",
    icon: Volume2,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/video/ogg-to-mp3",
  },
  {
    title: "MP4 to MOV",
    description: "Video Tools",
    paragraph: "Convert MP4 to MOV",
    icon: Volume2,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/video/mp4-to-mov",
  },
  {
    title: "MOV to GIF",
    description: "Video Tools",
    paragraph: "Convert MOV to GIF",
    icon: ImageIcon, // Add icon
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/mov-to-gif",
  },
  {
    title: "AVI to MP4",
    description: "Video Tools",
    paragraph: "Convert AVI to MP4",
    icon: Volume2,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/video/avi-to-mp4",
  },
  {
    title: "MP4 to WEBM",
    description: "Video Tools",
    paragraph: "Convert MP4 to WEBM",
    icon: Volume2, // Add icon
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/video/mp4-to-webm",
  },
  {
    title: "MOV to MP3",
    description: "Video Tools",
    paragraph: "Convert MOV to MP3 audio",
    icon: Volume2,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/video/mov-to-mp3",
  },
  {
    title: "MP4 to WAV",
    description: "Video Tools",
    paragraph: "Convert MP4 to WAV audio",
    icon: File,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/mp4-to-wav",
  },
  {
    title: "M4A to WAV",
    description: "Video Tools",
    paragraph: "Convert M4A to WAV audio",
    icon: Volume2, // Add icon
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/m4a-to-wav",
  },
  {
    title: "Convert Video Format",
    description: "Video Tools",
    paragraph: "Convert video files from one format to another",
    icon: Video,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/convert-video-format",
  },
  {
    title: "GIF to MP4",
    description: "Video Tools",
    paragraph: "Convert GIF to MP4 video",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/gif-to-mp4",
  },
  {
    title: "Essay Writer",
    description: "AI Write",
    paragraph: "Easily create an essay with AI",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/essay-writer",
  },
  {
    title: "Content Improver",
    description: "AI Write",
    paragraph: "Improve your content",
    divColor: "#E9F9EE",
    iconColor: "#27AE60",
    icon: FileText,
    link: "/write/content-improver",
  },
  {
    title: "Paragraph Writer",
    description: "AI Write",
    paragraph: "Paragraph Writer",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/paragraph-writer",
  },
  {
    title: "Paragraph Completer",
    description: "AI Write",
    paragraph: "Paragraph Completer",
    divColor: "#E9F9EE",
    iconColor: "#27AE60",
    icon: FileText,
    link: "/write/paragraph-completer",
  },
  {
    title: "Story Generator",
    description: "AI Write",
    paragraph: "Generate a Story",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/story-generator",
  },
  {
    title: "Grammar Fixer",
    description: "AI Write",
    paragraph: "Easily fix the grammar in a block of text",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/grammar-fixer",
  },
  {
    title: "Sentence Rewriter",
    description: "AI Write",
    paragraph: "Sentence Rewriter",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/sentence-rewriter",
  },
  {
    title: "Content Summarizer",
    description: "AI Write",
    paragraph: "Summarize text",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/content-summarizer",
  },
  {
    title: "Article Writer",
    description: "AI Write",
    paragraph: "Create an article from a title",
    divColor: "#E9F9EE",
    iconColor: "#27AE60",
    icon: FileText,
    link: "/write/article-writer",
  },
  {
    title: "YouTube Script Writer",
    description: "AI Write",
    paragraph: "Generate a YouTube script",
    divColor: "#E9F9EE",
    iconColor: "#27AE60",
    icon: FileText,
    link: "/write/youtube-script-writer",
  },
  {
    title: "Tone of Voice",
    description: "AI Write",
    paragraph: "Tone of Voice Tool",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/tone-of-voice",
  },
  {
    title: "Instagram Caption Generator",
    description: "AI Write",
    paragraph: "Generate Instagram caption",
    divColor: "#E9F9EE",
    iconColor: "#27AE60",
    icon: FileText,
    link: "/write/instagram-caption-generator",
  },
  {
    title: "Paragraph Rewriter",
    description: "AI Write",
    paragraph: "Rephrase a paragraph",
    divColor: "#E9F9EE",
    iconColor: "#27AE60",
    icon: FileText,
    link: "/write/paragraph-rewriter",
  },
  {
    title: "Explain it",
    description: "AI Write",
    paragraph: "Explain it like I’m five",
    icon: FileText,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/write/explain-like-five",
  },
  {
    title: "Article Generator",
    description: "AI Write",
    paragraph: "AI SEO Optimized Article Generator",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/article-generator",
  },
  {
    title: "Content Shortener",
    description: "AI Write",
    paragraph: "Resize your content",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/content-shortener",
  },
  {
    title: "Translate",
    description: "AI Write",
    paragraph: "Easily Translate Text",
    icon: FileText,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/write/translate",
  },
  {
    title: "LinkedIn Post Generator",
    description: "AI Write",
    paragraph: "Generate LinkedIn post",
    icon: File,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/write/linkedin-post-generator",
  },
  {
    title: "Title Rewriter",
    description: "AI Write",
    paragraph: "Rewrite your article title",
    icon: FileText,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/write/title-rewriter",
  },
  {
    title: "Business Name Generator",
    description: "AI Write",
    paragraph: "Generate a business name for your idea",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/business-name-generator",
  },
  {
    title: "Blog Post Ideas",
    description: "AI Write",
    paragraph: "Write Blog Post Ideas",
    icon: File,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/write/post-ideas",
  },
  {
    title: "Blog Post Generator",
    description: "AI Write",
    paragraph: "AI SEO Post Generator",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/post-generator",
  },
  {
    title: "Content Paraphraser",
    description: "AI Write",
    paragraph: "Paraphrasing Content",
    icon: File,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/write/paraphrasing",
  },
  {
    title: "Business Plan Generator",
    description: "AI Write",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/business-plan-generator",
  },
  {
    title: "Cold Email Write",
    description: "AI Write",
    paragraph: "Write cold email",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/cold-email-writer",
  },
  {
    title: "AI Rephraser",
    description: "AI Write",
    paragraph: "AI Rephraser Content",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/ai-rephraser",
  },
  {
    title: "Meta Description Generator",
    description: "AI Write",
    paragraph: "Generate meta description for your article",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/meta-description-generator",
  },
  {
    title: "Article Rewriter",
    description: "AI Write",
    paragraph: "Rewrite an article",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/article-rewriter",
  },
  {
    title: "Blog Outline Generator",
    description: "AI Write",
    paragraph: "Write Blog Outline",
    icon: File,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/write/blog-outline",
  },
  {
    title: "Content Planner",
    description: "AI Write",
    paragraph: "Generate a simple content plan",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/content-planner",
  },
  {
    title: "Content Brief Generator",
    description: "AI Write",
    paragraph: "Generate content brief for your article title",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/content-brief-generator",
  },
  {
    title: "Real Estate Descriptions",
    description: "AI Write",
    paragraph: "Generate Real Estate Descriptions",
    icon: File,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/write/real-estate-description",
  },
  {
    title: "Post Writer",
    description: "AI Write",
    paragraph: "Generate a blog post",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/post-writer",
  },
  {
    title: "Summarize Pdf",
    description: "Pdf Tools",
    paragraph: "Summarize Pdf Document",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/summarizer",
  },
  {
    title: "Twitter Generator",
    description: "AI Write",
    paragraph: "Twitter generator",
    icon: FileText,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/write/ai-twitter-generator",
  },
  {
    title: "AI Detector",
    description: "AI Write",
    paragraph: "AI Content Detector",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/ai-detector",
  },
  {
    title: "Business Slogan Generator",
    description: "AI Write",
    paragraph: "Generate business slogan",
    icon: FileText,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/write/business-slogan-generator",
  },
  {
    title: "Instagram Story Idea",
    description: "AI Write",
    paragraph: "Generate Instagram story ideas",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/instagram-story-ideas",
  },
  {
    title: "TikTok Script Writer",
    description: "AI Write",
    paragraph: "TikTok Script Writer",
    icon: FileText,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/write/tiktok-script-writer",
  },
  {
    title: "FB Headline Generator",
    description: "AI Write",
    paragraph: "Generate Facebook ad headlines",
    icon: FileText,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/write/facebook-ad-headlines",
  },
  {
    title: "Press Release Generator",
    description: "AI Write",
    paragraph: "Generate a press release",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/press-release-generator",
  },
  {
    title: "Trivia Generator",
    description: "AI Write",
    paragraph: "Generate Trivia Questions",
    icon: FileText,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/write/trivia-generator",
  },
  {
    title: "FAQ Generator",
    description: "AI Write",
    paragraph: "Generate FAQ for a blog",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/faq-generator",
  },
  {
    title: "Podcast Script Writer",
    description: "AI Write",
    paragraph: "Podcast Script Generator",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/podcast-writer",
  },
  {
    title: "Blog Post Rewriter",
    description: "AI Write",
    paragraph: "Rephrase a blog post",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/post-rewriter",
  },

  {
    title: "Landing Page Copy Generator",
    description: "AI Write",
    paragraph: "Generate landing page copy",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/landing-page-copy",
  },
  {
    title: "Poll Generator",
    description: "AI Write",
    paragraph: "AI Generated Polls",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/poll-generator",
  },
  {
    title: "Bill of Sale",
    description: "AI Write",
    paragraph: "Generate bill of sale",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/bill-sale-generator",
  },
  {
    title: "Purchase Agreement",
    description: "AI Write",
    paragraph: "Generate purchase agreement",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/purchase-agreement-generator",
  },
  {
    title: "NDA Generator",
    description: "AI Write",
    paragraph: "Generate NDA",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/nda-generator",
  },
  {
    title: "Privacy Policy Generator",
    description: "AI Write",
    paragraph: "Generate privacy policy",
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    icon: FileText,
    link: "/write/privacy-policy-generator",
  },
  {
    title: "Summarize YouTube",
    description: "AI Write",
    paragraph: "Summarize YouTube Video",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/write/summarize-youtube",
  },
  {
    title: "Word Counter",
    description: "AI Write",
    paragraph: "Count words in your text",
    divColor: "#E9F9EE",
    iconColor: "#27AE60",
    icon: FileText,
    link: "/write/word-counter",
  },
  {
    title: "AI Chat",
    description: "AI Write",
    paragraph: "Chat with AI",
    icon: MessageCircle,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/write/ai-chat",
  },
  {
    title: "AI Image Generator",
    description: "Image Tools",
    paragraph: "AI Image Generator",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/ai-image-generator",
  },
  {
    title: "Remove Background from Image",
    description: "Image Tools",
    paragraph: "Easily Remove the Background from an image",
    icon: ImageIcon,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/remove-background",
  },
  {
    title: "PDF to JPG",
    description: "Pdf Tools",
    paragraph: "Convert PDF to JPG and download each page as an image",
    icon: File,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/pdf-to-jpg",
  },
  {
    title: "Upscale Image",
    description: "Image Tools",
    paragraph: "Increase the resolution of your image",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/upscale-image",
  },
  {
    title: "Image To Text",
    description: "Image Tools",
    paragraph: "Extract text from images",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image-to-text",
  },
  {
    title: "Remove Watermark",
    description: "Image Tools",
    paragraph: "Remove watermark from photo",
    icon: ImageIcon,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/remove-watermark",
  },
  {
    title: "Compress Image Size",
    description: "Image Tools",
    paragraph: "Compress your image",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/compress-image",
  },
  {
    title: "Resize Image Dimensions",
    description: "Image Tools",
    paragraph: "Resize your image",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/resize-image",
  },
  {
    title: "Profile Photo Maker",
    description: "Image Tools",
    paragraph: "Create round profile photo from image",
    icon: CircleUser,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/profile-photo-maker",
  },
  {
    title: "Remove Objects from Photo",
    description: "Image Tools",
    paragraph: "Remove objects from photo",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/remove-objects-photo",
  },
  {
    title: "HEIC to JPG",
    description: "Image Tools",
    paragraph: "Convert an iPhone HEIC image to JPG",
    icon: ImageIcon,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/heic-to-jpg",
  },
  {
    title: "Blur Background",
    description: "Image Tools",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/blur-background",
  },
  {
    title: "Remove Person from Photo",
    description: "Image Tools",
    paragraph: "Remove a person from photo",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/remove-person-photo",
  },
  {
    title: "WebP to JPG",
    description: "Image Tools",
    paragraph: "Upload a WebP image and download as JPG",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/webp-to-jpg",
  },
  {
    title: "Unblur Image",
    description: "Image Tools",
    paragraph: "Unblur your image",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/unblur-image",
  },
  {
    title: "Cleanup Picture",
    description: "Image Tools",
    paragraph: "Cleanup picture",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/cleanup-picture",
  },
  {
    title: "Colorize Photo",
    description: "Image Tools",
    paragraph: "Colorize your photo",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/colorize-photo",
  },
  {
    title: "PNG to JPG",
    description: "Image Tools",
    paragraph: "Convert a PNG image to JPG",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/png-to-jpg",
  },
  {
    title: "WEBP to PNG",
    description: "Image Tools",
    paragraph: "Convert a WEBP image to PNG",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/webp-to-png",
  },
  {
    title: "Crop Image",
    description: "Image Tools",
    paragraph: "Crop your image",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/crop-image",
  },
  {
    title: "Make Background Transparent",
    description: "Image Tools",
    paragraph: "Make background transparent",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/make-background-transparent",
  },
  {
    title: "Combine Images",
    description: "Image Tools",
    paragraph: "Combine multiple images online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/combine-images",
  },
  {
    title: "JPG to PNG",
    description: "Image Tools",
    paragraph: "Convert a JPG image to PNG",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/jpg-to-png",
  },
  {
    title: "PNG to WEBP",
    description: "Image Tools",
    paragraph: "Convert a PNG image to WEBP",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/png-to-webp",
  },
  {
    title: "JPG to WEBP",
    description: "Image Tools",
    paragraph: "Convert a JPG image to WEBP",
    icon: ImageIcon,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/jpg-to-webp",
  },
  {
    title: "Make Round Image",
    description: "Image Tools",
    paragraph: "Make round images",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/make-round-image",
  },
  {
    title: "PNG to SVG",
    description: "Image Tools",
    paragraph: "Convert a PNG image to SVG",
    icon: ImageIcon,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/png-to-svg",
  },
  {
    title: "Black & White",
    description: "Image Tools",
    paragraph: "Make your photo black & white",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/black-white",
  },
  {
    title: "Add Text to an Image",
    description: "Image Tools",
    paragraph: "Add text to an image online",
    icon: ImageIcon,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/add-text-to-image",
  },
  {
    title: "JPG to SVG",
    description: "Image Tools",
    paragraph: "Convert a JPG image to SVG",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/jpg-to-svg",
  },
  {
    title: "HEIC to PNG",
    description: "Image Tools",
    paragraph: "Convert a HEIC image to PNG",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/heic-to-png",
  },
  {
    title: "Image Splitter",
    description: "Image Tools",
    paragraph: "Cut image into pieces",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/image-splitter",
  },
  {
    title: "Add Images",
    description: "Image Tools",
    paragraph: "Add images to Image",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/add-images",
  },
  {
    title: "Pixelate Image",
    description: "Image Tools",
    paragraph: "Pixelate your photo",
    icon: ImageIcon,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/pixelate-image",
  },
  {
    title: "Translate Image",
    description: "Image Tools",
    paragraph: "Translate your image",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/translate-image",
  },
  {
    title: "Add Border to Image",
    description: "Image Tools",
    paragraph: "Add a border to your image",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/add-border-to-image",
  },
  {
    title: "Collage Maker",
    description: "Image Tools",
    paragraph: "Create Photo Collages Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/collage-maker",
  },
  {
    title: "SVG to PNG",
    description: "Image Tools",
    paragraph: "Convert a SVG image to PNG free",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/svg-to-png",
  },
  {
    title: "GIF to MP4",
    description: "Video Tools",
    paragraph: "Convert animated GIF to MP4 Online",
    icon: Video,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/gif-to-mp4",
  },
  {
    title: "JPG to GIF",
    description: "Image Tools",
    paragraph: "Convert a JPG Image to GIF Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/jpg-to-gif",
  },
  {
    title: "Flip Image",
    description: "Image Tools",
    paragraph: "Flip Image",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/flip-image",
  },
  {
    title: "TIFF to JPG",
    description: "Image Tools",
    paragraph: "Convert a TIFF Image to JPG Online",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/tiff-to-jpg",
  },
  {
    title: "WEBP to GIF",
    description: "Image Tools",
    paragraph: "Convert a WEBP Image to GIF Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/webp-to-gif",
  },
  {
    title: "View Metadata",
    description: "Image Tools",
    paragraph: "View metadata for your image",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/view-metadata",
  },
  {
    title: "PNG to EPS",
    description: "Image Tools",
    paragraph: "Convert a PNG Image to EPS Online",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/png-to-eps",
  },
  {
    title: "JPG to TIFF",
    description: "Image Tools",
    paragraph: "Convert a JPG Image to TIFF Online",
    icon: ImageIcon,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/jpg-to-tiff",
  },
  {
    title: "PNG to GIF",
    description: "Image Tools",
    paragraph: "Convert a PNG Image to GIF Online",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/png-to-gif",
  },
  {
    title: "PSD to JPG",
    description: "Image Tools",
    paragraph: "Convert a PSD Image to JPG Online",
    icon: ImageIcon,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/psd-to-jpg",
  },
  {
    title: "EPS to PNG",
    description: "Image Tools",
    paragraph: "Convert an EPS image to PNG",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/eps-to-png",
  },
  {
    title: "PSD to PNG",
    description: "Image Tools",
    paragraph: "Convert a PSD Image to PNG Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/psd-to-png",
  },
  {
    title: "Chart Maker",
    description: "Image Tools",
    paragraph: "Download a chart as image",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/chart-maker",
  },
  {
    title: "GIF to JPG",
    description: "Image Tools",
    paragraph: "Convert a GIF Image to JPG Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/gif-to-jpg",
  },
  {
    title: "TIFF to PNG",
    description: "Image Tools",
    paragraph: "Convert a TIFF Image to PNG Online",
    icon: ImageIcon, // Document icon
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/tiff-to-png",
  },
  {
    title: "GIF to PNG",
    description: "Image Tools",
    paragraph: "Convert a GIF Image to PNG Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/gif-to-png",
  },
  {
    title: "PSD to AI",
    description: "Image Tools",
    paragraph: "Convert a PSD Image to AI Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/psd-to-ai",
  },
  {
    title: "EPS to JPG",
    description: "Image Tools",
    paragraph: "Convert an EPS Image to JPG Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/eps-to-jpg",
  },
  {
    title: "PNG to TIFF",
    description: "Image Tools",
    paragraph: "Convert a PNG Image to TIFF Online",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/png-to-tiff",
  },
  {
    title: "EPS to SVG",
    description: "Image Tools",
    paragraph: "Convert a EPS Image to SVG Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/eps-to-svg",
  },
  {
    title: "Font Awesome to PNG",
    description: "Image Tools",
    paragraph: "Convert Font Awesome to PNG",
    icon: FileText,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/font-awesome-to-png",
  },
  {
    title: "TIFF To Text",
    description: "Image Tools",
    paragraph: "TIFF To Text",
    icon: FileText,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/tiff-to-text",
  },
  {
    title: "GIF to APNG",
    description: "Image Tools",
    paragraph: "Convert animated GIF Image to APNG Online",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/gif-to-apng",
  },
  {
    title: "PSD to SVG",
    description: "Image Tools",
    paragraph: "Convert a PSD Image to SVG Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/psd-to-svg",
  },
  {
    title: "TIFF to SVG",
    description: "Image Tools",
    paragraph: "Convert a TIFF Image to SVG Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/tiff-to-svg",
  },
  {
    title: "JPG to AVIF",
    description: "Image Tools",
    paragraph: "Convert a JPG Image to AVIF Online",
    icon: ImageIcon,
    iconColor: "#3D99F5",
    divColor: "#E2F0FE",
    link: "/jpg-to-avif",
  },
  {
    title: "VSDX To PDF",
    description: "Image Tools",
    paragraph: "VSDX To PDF",
    icon: FileText,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/vsdx-to-pdf",
  },
  {
    title: "VSDX To DOCX",
    description: "Image Tools",
    paragraph: "VSDX To DOCX",
    icon: FileText,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/vsdx-to-docx",
  },
  {
    title: "VSDX To PPTX",
    description: "Image Tools",
    paragraph: "VSDX To PPTX",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/vsdx-to-pptx",
  },
  {
    title: "PNG to AVIF",
    description: "Image Tools",
    paragraph: "Convert a PNG Image to AVIF Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/png-to-avif",
  },
  {
    title: "VSD To PDF",
    description: "Image Tools",
    paragraph: "VSD To PDF",
    icon: ImageIcon,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/vsd-to-pdf",
  },
  {
    title: "VSDX To JPG",
    description: "Image Tools",
    paragraph: "VSDX To JPG",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/vsdx-to-jpg",
  },
  {
    title: "VSD To PPTX",
    description: "Image Tools",
    paragraph: "VSD To PPTX",
    icon: FileText,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/vsd-to-jpg",
  },
  {
    title: "WEBP to AVIF",
    description: "Image Tools",
    paragraph: "Convert a WEBP Image to AVIF Online",
    icon: ImageIcon,
    iconColor: "#E2C740",
    divColor: "#FEF9E2",
    link: "/webp-to-avif",
  },
  {
    title: "VSD To DOCX",
    description: "Image Tools",
    paragraph: "VSD To DOCX",
    icon: FileText,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/vsd-to-docx",
  },
  {
    title: "GIF to AVIF",
    description: "Image Tools",
    paragraph: "Convert a GIF Image to AVIF Online",
    icon: ImageIcon,
    iconColor: "#10D0D5",
    divColor: "#E3FCFD",
    link: "/gif-to-avif",
  },
  {
    title: "HEIC to AVIF",
    description: "Image Tools",
    paragraph: "Convert a HEIC Image to AVIF Online",
    icon: ImageIcon,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/heic-to-avif",
  },
  {
    title: "Excel to PDF",
    description: "Converter Tools",
    paragraph: "Convert Excel to PDF",
    icon: File,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/file/excel-to-pdf",
  },
  {
    title: "CSV to Excel",
    description: "Converter Tools",
    paragraph: "Convert CSV to Excel",
    icon: File,
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    link: "/file/csv-to-excel",
  },
  {
    title: "Split Excel",
    description: "Converter Tools",
    paragraph: "Split into one or multiple Excel files",
    icon: File,
    divColor: "#E9F9EE",
    iconColor: "#27AE60",
    link: "/file/split-excel",
  },
  {
    title: "Excel to XML",
    description: "Converter Tools",
    paragraph: "Convert Excel to XML",
    icon: File,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/file/excel-to-xml",
  },
  {
    title: "CSV to XML",
    description: "Converter Tools",
    paragraph: "Convert CSV to XML",
    icon: File,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/file/csv-to-xml",
  },
];
export const featuredArray = [
  {
    title: "XML to Excel",
    description: "Converter Tools",
    paragraph: "Convert XML to Excel",
    icon: File,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/file/xml-to-excel",
  },
  {
    title: "JSON to XML",
    description: "Converter Tools",
    paragraph: "Convert JSON to XML",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/file/json-to-xml",
  },
  {
    title: "Split CSV",
    description: "Converter Tools",
    paragraph: "Split into one or multiple PDF files",
    icon: File,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/file/split-csv",
  },
  {
    title: "CSV to JSON",
    description: "Converter Tools",
    paragraph: "Convert CSV to JSON",
    icon: File,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/file/csv-to-json",
  },
  {
    title: "XML to JSON",
    description: "Converter Tools",
    paragraph: "Convert XML to JSON",
    icon: File,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/file/xml-to-json",
  },
];

export const converterTools = [
  {
    title: "Excel to PDF",
    description: "Converter Tools",
    paragraph: "Convert Excel to PDF",
    icon: File,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/file/excel-to-pdf",
  },
  {
    title: "CSV to Excel",
    description: "Converter Tools",
    paragraph: "Convert CSV to Excel",
    icon: File,
    divColor: "#E8F2FF",
    iconColor: "#1A8FE3",
    link: "/file/csv-to-excel",
  },
  {
    title: "Split Excel",
    description: "Converter Tools",
    paragraph: "Split into one or multiple Excel files",
    icon: File,
    divColor: "#E9F9EE",
    iconColor: "#27AE60",
    link: "/file/split-excel",
  },
  {
    title: "XML to Excel",
    description: "Converter Tools",
    paragraph: "Convert XML to Excel",
    icon: File,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/file/xml-to-excel",
  },
  {
    title: "JSON to XML",
    description: "Converter Tools",
    paragraph: "Convert JSON to XML",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/file/json-to-xml",
  },
  {
    title: "Split CSV",
    description: "Converter Tools",
    paragraph: "Split into one or multiple PDF files",
    icon: File,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/file/split-csv",
  },
  {
    title: "XML to CSV",
    description: "Converter Tools",
    paragraph: "Convert XML to CSV",
    icon: File,
    iconColor: "#FF7919",
    divColor: "#FFEDE0",
    link: "/file/xml-to-csv",
  },
  {
    title: "Excel to CSV",
    description: "Converter Tools",
    paragraph: "Convert Excel to CSV",
    icon: File,
    iconColor: "#79DC47",
    divColor: "#ECFAE5",
    link: "/file/excel-to-csv",
  },
  {
    title: "CSV to JSON",
    description: "Converter Tools",
    paragraph: "Convert CSV to JSON",
    icon: File,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/file/csv-to-json",
  },
  {
    title: "XML to JSON",
    description: "Converter Tools",
    paragraph: "Convert XML to JSON",
    icon: File,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/file/xml-to-json",
  },
  {
    title: "Excel to XML",
    description: "Converter Tools",
    paragraph: "Convert Excel to XML",
    icon: File,
    iconColor: "#624BD8",
    divColor: "#E9E6F9",
    link: "/file/excel-to-xml",
  },
  {
    title: "CSV to XML",
    description: "Converter Tools",
    paragraph: "Convert CSV to XML",
    icon: File,
    iconColor: "#E24841",
    divColor: "#FBE6E5",
    link: "/file/csv-to-xml",
  },
];
